### ISSUE TITLE
Feature request for: /web3-data-api/evm/resolve-api

### ISSUE THREAD

**Issue by MCSWebDev** [MoralisWeb3/docs#148]
**Is your feature request related to a problem? Please describe.**
The page does NOT actually explain what the API does. It says (and I quote): "Resolve API
What is the Resolve API?
The Resolve API is a set of endpoints that helps Web3 developers resolve ENS names and Unstoppable domains.
Resolve API Features
The Resolve API provides the following functionality out of the box to power the dapps you are building:
Resolve an ETH address and find the ENS name.
Resolving an Unstoppable domain and getting the address."

**The word "resolve" is used 7 times, mainly to define itself!!**

**Describe the solution you'd like**
Can we PLEASE actually define and explain what it means to resolve, what the process is, what use cases might be, and what components or processes are involved in 'resolving'?
**Describe alternatives you've considered**
Doing the footwork myself... tracking down several definitions from OTHER sites (meaning i navigate away from here and get distracted, also I'm then kinda irked at this site and may wish to engage a competitor of yours instead) and then considering those sources to verify i have accurately triangulated a comprehensive explanation.
**Additional context**
It is NEVER acceptable to define a term by using the term in question... regardless of how 'obvious' it may seem, it is not a good idea to assume knowledge in the context of documentation.

**Comment by YosephKS** [comment]
Hey @MCSWebDev,

Thanks for creating the issue here 🙌🏼 

Resolving is a very particular and commonly used word when working with decentralized name systems such as ENS and Unstoppable domains. As far as now, most devs that are using our API have any trouble understanding the usage of our API and therefore the phrase shall not be changed.

We definitely use the assumption of knowledge on the word here as people that use the Resolve API tend to be the one that is already familiar with how ENS and Unstoppable domain works. For those that are trying to understand the concept as it should, they should use the ENS documentation instead for such a purpose.

However, I can include a reference to the information, but I will not include any definition of what **Resolve** is here as it is what the ENS docs are for, and the Moralis docs are only for explaining what the APIs are for. For use cases and others looks like it should be clear enough for those that are already working with ENS or Unstoppable domain and therefore no changes will be made on those as well.

If you have any other issues found, feel free to create a new one, I'll provide the reference soon and open a PR for this.

**Comment by YosephKS** [comment]
Btw added some references to ENS and Unstoppable + about resolving names 🙌🏼
